config-version: 1
properties:
  chat-prefix: '&7[&dCSF&7] '
  
  #Database to use, sqlite or mysql. 
  db-type: sqlite
  
  #Default permission access. op=ops get full access by default, true=everyone gets full access by default, false=noone gets access by default (permissions only).
  permission-default: op
  
  # Check for new version on startup.
  check-new-version: true
  
  # Help the developer know how popular the plugin is.
  use-metrics: true
  
  # Show debug messages.
  debug-messages: true
  
  # Auto add shop upon creation to our database. (only means of adding shops atm)
  auto-register: true
  
  #Decimal places to round prices.
  price-rounding: 2
  
  # When a chunk is loaded for the first time this session, check if any known shops are missing, delete if so, update stock count if not.
  verify-chunk-shops: true
  
  # Number of shops to display in the search/buy/sell commands.
  search-results: 5
  
  # Number of results to show in the transactions commands. 
  transaction-results: 10
  
  # If a shop owner has multiple shops for the same item, show only one.
  one-owner-per-results: true
  
  # Name of your admin shop, to bypass our supply/balance check.
  admin-shop: "Administrator Shop"
  
  # Prevent full chests from being listed in the sell command. 
  exclude-full-chests-from-sell: true
  
  #If a player is online, use their nickname. 
  show-nicknames: true
  
  # Monitor hopper events to update shop stock.
  hopper-detection: true
  
  # Log transactions to DB
  log-transactions: true
  
  #Add whitespaces after variables so messages better line up.
  white-space-results: true
  
  # How old in seconds should we include in the transaction commands.
  transaction-age-include: 604800
  
# MySQL DB information.
mysql:
  hostname: localhost
  username: root
  password: CHANGEME
  port: 3306
  database: minecraft
  prefix: CSF_
  
  # Your iConomy db table, to confirm a shop can afford to an item. Set to false if you don't want to use iConomy with MySQL.
  iConomy_table: false
